from enums import Model, Dataset, Prompt
from main import run_test_bed
run_test_bed(Dataset.GSM8K, Model.Llama38B, Model.WizardMath7B, Prompt.TraceOfThought, 129)
run_test_bed(Dataset.GSM8K, Model.Llama38B, Model.Zephyr, Prompt.TraceOfThought, 0)
run_test_bed(Dataset.GSM8K, Model.Llama38B, Model.Llama27BChat, Prompt.TraceOfThought, 0)
run_test_bed(Dataset.GSM8K, Model.Llama38B, Model.Llama38B, Prompt.TraceOfThought, 0)
run_test_bed(Dataset.GSM8K, Model.GPT4, Model.GPT4, Prompt.TraceOfThought, 0)
run_test_bed(Dataset.GSM8K, Model.GPT4, Model.GPT3point5, Prompt.TraceOfThought, 0)
run_test_bed(Dataset.GSM8K, Model.GPT4, Model.WizardMath7B, Prompt.TraceOfThought, 0)
run_test_bed(Dataset.GSM8K, Model.GPT4, Model.Zephyr, Prompt.TraceOfThought, 0)
run_test_bed(Dataset.GSM8K, Model.GPT4, Model.Llama27BChat, Prompt.TraceOfThought, 0)
run_test_bed(Dataset.GSM8K, Model.GPT4, Model.Llama38B, Prompt.TraceOfThought, 0)
run_test_bed(Dataset.MATH, Model.Llama38B, Model.GPT4, Prompt.TraceOfThought, 0)
run_test_bed(Dataset.MATH, Model.Llama38B, Model.GPT3point5, Prompt.TraceOfThought, 0)
run_test_bed(Dataset.MATH, Model.Llama38B, Model.WizardMath7B, Prompt.TraceOfThought, 0)
run_test_bed(Dataset.MATH, Model.Llama38B, Model.Zephyr, Prompt.TraceOfThought, 0)
run_test_bed(Dataset.MATH, Model.Llama38B, Model.Llama27BChat, Prompt.TraceOfThought, 0)
run_test_bed(Dataset.MATH, Model.Llama38B, Model.Llama38B, Prompt.TraceOfThought, 0)
run_test_bed(Dataset.MATH, Model.GPT4, Model.GPT4, Prompt.TraceOfThought, 0)
run_test_bed(Dataset.MATH, Model.GPT4, Model.GPT3point5, Prompt.TraceOfThought, 0)
run_test_bed(Dataset.MATH, Model.GPT4, Model.WizardMath7B, Prompt.TraceOfThought, 0)
run_test_bed(Dataset.MATH, Model.GPT4, Model.Zephyr, Prompt.TraceOfThought, 0)
run_test_bed(Dataset.MATH, Model.GPT4, Model.Llama27BChat, Prompt.TraceOfThought, 0)
run_test_bed(Dataset.MATH, Model.GPT4, Model.Llama38B, Prompt.TraceOfThought, 0)